In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [4]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [5]:
arr1.dtype

dtype('float64')

In [6]:
arr2.dtype

dtype('int32')

In [7]:
# Casting an array

In [8]:

arr = np.array([1,2,3,4,5])

In [9]:
arr.dtype

dtype('int64')

In [10]:
float_arr = arr.astype(np.float64)

In [11]:
float_arr

array([1., 2., 3., 4., 5.])

In [12]:
float_arr.dtype

dtype('float64')

In [13]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [14]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [15]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [18]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.str_)

In [19]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])