In [1]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]

np.int64(5)

In [6]:
arr[5:8]

array([5, 6, 7])

In [7]:
arr[5:8] = 12

In [8]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
arr_slice = arr[5:8]

In [10]:
arr_slice

array([12, 12, 12])

In [11]:
arr_slice[1] = 12345

In [12]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [13]:
arr_slice[:] = 64

In [14]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [15]:
arr_copy = arr[5:8].copy()

In [16]:
arr_copy

array([64, 64, 64])

In [17]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [18]:
arr2d[2]

array([7, 8, 9])

In [19]:
arr2d[0][2]

np.int64(3)

In [20]:
arr2d[0,2]

np.int64(3)

In [24]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [25]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
old_values = arr3d[0].copy()

In [28]:
arr3d[0] = 42

In [29]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d[0] = old_values

In [31]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr3d[1,0]

array([7, 8, 9])

In [33]:
x = arr3d[1]

In [34]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [35]:
x[0]

array([7, 8, 9])