In [1]:
import numpy as np

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [7]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [11]:
lower_dim_slice = arr2d[1, :2]

In [12]:
lower_dim_slice.shape

(2,)

In [13]:
arr2d[:2,2]

array([3, 6])

In [14]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [15]:
arr2d[:2, 1:] = 0

In [16]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [17]:
arr2_1d = np.array([[1,0,0],[2,0,0],[3,0,0]])

In [18]:
arr2_1d

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [19]:
arr2_1d[:2, 1:]

array([[0, 0],
       [0, 0]])

In [21]:
arr2_1d[0]

array([1, 0, 0])

In [22]:
arr2_1d[1]

array([2, 0, 0])

In [23]:
arr2_1d[2]

array([3, 0, 0])

In [24]:
arr2_1d[0,:]

array([1, 0, 0])

In [25]:
arr2_1d[0:,:]

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [26]:
arr2_1d[1:,:]

array([[2, 0, 0],
       [3, 0, 0]])

In [27]:
arr2_1d[:1,0:]

array([[1, 0, 0]])

In [28]:
arr2_1d[:1,:1]

array([[1]])

In [29]:
arr2_1d[:2,:1]

array([[1],
       [2]])

In [31]:
arr2_1d[:3,:2]

array([[1, 0],
       [2, 0],
       [3, 0]])

In [32]:
arr2_1d[:2,1:]

array([[0, 0],
       [0, 0]])